### ISSUE TITLE
Missing parameters in the documentation

### ISSUE THREAD

**Issue by gjankowiak** [fcdimitr/LFRBenchmarkGraphs.jl#4]
The documentation is missing some of the keyword parameters, for example `mixing_parameter`.

**Comment by fcdimitr** [comment]
Thank you very much, @gjankowiak! Could you check the PR in #5 and let me know if this covers this issue?

**Comment by gjankowiak** [comment]
It looks good, thank you! What happens if one passes both `defect=True` and `excess=True`?

**Comment by fcdimitr** [comment]
Both options cannot be used at the same time. I will add this comment in the docs. Thanks!

**Comment by fcdimitr** [comment]
I merged the changes into the main branch. Version `1.0.1` should be in the registry shortly. Thank you!
