### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by gjankowiak** [fcdimitr/LFRBenchmarkGraphs.jl#8]
Apart from Lancichinetti's code/paper, I'd like to be able to cite this package. Have you thought about adding a [CITATION.cff](https://citation-file-format.github.io/) file to the repository? You can find a generator [here](https://citation-file-format.github.io/cff-initializer-javascript/#/).

**Comment by fcdimitr** [comment]
Thank you very much, @gjankowiak! I created a CITATION.cff file and also got a Zenodo DOI so that this package can be cited.
